### ISSUE TITLE
installation problem 

### ISSUE THREAD

**Issue by NomiCentarix** [getzlab/rnaseqc#66]
Hello, This is the first time I use rnaseqc.

When I do the make command I get the following error:

```
src/GTF.cpp:13:10: fatal error: boost/regex.hpp: No such file or directory
   13 | #include <boost/regex.hpp>
```

I am working on Ubuntu 21.04 on Google Cloud. 

Thanks,
Nomi

**Comment by NomiCentarix** [comment]
ok, I missed the static binaries version... 
You can close the issue
